app/__init__.py
from flask import Flask, g

from app.db import get_db


def create_app():
    app = Flask(__name__)

    with app.app_context():
        get_db(is_server_start=True)

    @app.teardown_appcontext
    def close_connection(exception):
        db = getattr(g, '_database', None)
        if db is not None:
            db.close()

    from app.categories import bp as categ_bp
    app.register_blueprint(categ_bp, url_prefix='/categories')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp, url_prefix='/')

    from app.spendings import bp as spend_bp
    app.register_blueprint(spend_bp, url_prefix='/spendings')

    @app.route('/test')
    def test_page():
        return "This is a test page"

    return app

app/categories/__init__.py
from flask import Blueprint

bp = Blueprint('categories', __name__)

from app.categories import routes

app/categories/routes.py
from flask import g, render_template, request, redirect, abort

from app.categories import bp
from app.db import get_category_db


@bp.route('/')
def get_categories():
    categories = get_category_db().get_categories()
    categories_dict = []
    for category in categories:
        categories_dict.append({
            "id": category[0],
            "name": category[1],
            "description": category[2],
            "color": category[3],
        })
    return render_template('categories/index.html', categories=categories_dict)


@bp.route('/create', methods=['GET', 'POST'])
def create_category():
    if request.method == 'GET':
        return render_template('categories/create.html')
    else:
        name = request.form.get('name')
        description = request.form.get('description')
        color = request.form.get('color')
        db = get_category_db()

        db.create_category(name=name, description=description, color=color)
        return redirect('/categories', code=302)


@bp.route('/edit/<int:category_id>', methods=['GET', 'POST'])
def edit_category(category_id):
    db = get_category_db()
    if request.method == 'GET':
        category = db.get_category(id=category_id)
        if category:
            print(category)
            return render_template('categories/edit.html', name=category[0], description=category[1], color=category[2])
        abort(404)
    else:
        name = request.form.get('name')
        description = request.form.get('description')
        color = request.form.get('color')

        db.edit_category(id=category_id, name=name, description=description, color=color)
        return redirect('/categories', code=302)


@bp.route('/delete/<int:category_id>', methods=['GET', 'POST'])
def delete_category(category_id):
    db = get_category_db()
    if request.method == 'GET':
        category = db.get_category(id=category_id)
        if category:
            return render_template('categories/delete.html', name=category[0], description=category[1], color=category[2])
        abort(404)
    else:
        db.delete_category(id=category_id)
        return redirect('/categories', code=302)

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('/', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template

from app.main import bp


@bp.route('/')
def get_index():
    # тут ваш темплейт
    return "Привіт з індекс сторінки"

app/spendings/__init__.py
from flask import Blueprint

bp = Blueprint('spendings', __name__)

from app.spendings import routes

app/spendings/routes.py
from flask import g, render_template, request, redirect, abort

from app.spendings import bp
from app.db import get_spending_db


@bp.route('/')
def get_spendings():
    spendings = get_spending_db().get_spendings()
    spendings_dict = []
    for spending in spendings:
        spendings_dict.append({
            "id": spending[0],
            "name": spending[1],
            "category": spending[2],
            "date": spending[3],
            "sum0": spending[4],
            "is_spending": spending[5],
        })
    return render_template('spendings/index.html', spendings=spendings_dict)


@bp.route('/create', methods=['GET', 'POST'])
def create_spending():
    if request.method == 'GET':
        return render_template('spendings/create.html')
    else:
        name = request.form.get('name')
        category = request.form.get('category')
        date = request.form.get('date')
        sum0 = request.form.get('sum0')
        spending_or_salary = request.form.get('spending_or_salary')
        db = get_spending_db()

        db.create_spending(name=name, category_id=category, date=date, spending=sum0, is_spending=spending_or_salary)
        return redirect('/spendings', code=302)


@bp.route('/edit/<int:spending_id>', methods=['GET', 'POST'])
def edit_spending(spending_id):
    db = get_spending_db()
    if request.method == 'GET':
        spending = db.get_spending(id=spending_id)
        if spending:
            print(spending)
            return render_template('spendings/edit.html', name=spending[1], category=spending[2], date=spending[3], sum0=spending[4], spending_or_salary=spending[5])
        abort(404)
    else:
        name = request.form.get('name')
        category = request.form.get('category')
        date = request.form.get('date')
        sum0 = request.form.get('sum')
        spending_or_salary = request.form.get('spending_or_salary')

        db.edit_spending(id=spending_id, name=name, category_id=category, date=date, spending=sum0, is_spending=spending_or_salary)
        return redirect('/spendings', code=302)


@bp.route('/delete/<int:spending_id>', methods=['GET', 'POST'])
def delete_spending(spending_id):
    db = get_spending_db()
    if request.method == 'GET':
        spending = db.get_spending(id=spending_id)
        if spending:
            return render_template('spendings/delete.html', name=spending[0], category=spending[1], date=spending[2], sum0=spending[4], spending_or_salary=spending[5])
        abort(404)
    else:
        db.delete_spending(id=spending_id)
        return redirect('/spendings', code=302)

app/templates/categories/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Create new category</h1>
  <form method="post">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" required> <br/>
    <label for="name">Description</label>
    <input type="text" name="description" id="description" required> <br/>
    <label for="name">Color</label>
    <input type="color" name="color" id="color" value="#FFFFFF" required> <br/>

    <button type="reset">Reset</button>
    <button type="submit">Submit</button>
  </form>
</body>
</html>

app/templates/categories/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Do you want to delete such category "{{ name }}"?</h1>
  <form method="post">
    <button><a href="{{ url_for('categories.get_categories') }}">No</a></button>
    <button type="submit">Yes</button>
  </form>
</body>
</html>

app/templates/categories/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Edit category</h1>
  <form method="post">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" value="{{ name }}"required> <br/>
    <label for="name">Description</label>
    <input type="text" name="description" id="description" value="{{ description }}" required> <br/>
    <label for="name">Color</label>
    <input type="color" name="color" id="color" value="{{ color }}" required> <br/>

    <button type="reset">Reset</button>
    <button type="submit">Submit</button>
  </form>
</body>
</html>

app/templates/categories/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Categories</title>
</head>
<body>
    <h1>Categories</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Color</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            {% for category in categories%}
             <tr style="background-color:{{ category.color }};">
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>{{ category.color }}</td>
                <td><button><a href="{{ url_for('categories.edit_category', category_id=category.id) }}">Edit</a></button></td>
                <td><button><a href="{{ url_for('categories.delete_category', category_id=category.id) }}">Delete</a></button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

app/templates/spendings/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Create new spending</h1>
  <form method="post">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" required> <br/>
    <label for="category">Category</label>
    <input type="text" name="category" id="category" required> <br/>
    <label for="date">Date</label>
    <input type="date" name="date" id="date" required> <br/>
    <label for="sum0">Sum</label>
    <input type="text" name="sum0" id="sum0" required> <br/>
    <label for="spending_or_salary">Is</label>
    <input type="text" name="spending_or_salary" id="spending_or_salary" required> <br/>

    <button type="reset">Reset</button>
    <button type="submit">Submit</button>
  </form>
</body>
</html>

app/templates/spendings/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Do you want to delete such spending "{{ name }}"?</h1>
  <form method="post">
    <button><a href="{{ url_for('spendings.get_spendings') }}">No</a></button>
    <button type="submit">Yes</button>
  </form>
</body>
</html>

app/templates/spendings/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Edit spending</h1>
  <form method="post">
    <label for="name">Name</label>
    <input type="text" name="name" id="name" value="{{ name }}" required> <br/>
    <label for="category">Category</label>
    <input type="text" name="category" id="category" value="{{ category }}" required> <br/>
    <label for="date">Date</label>
    <input type="date" name="date" id="date" value="{{ date }}" required> <br/>
    <label for="sum">Sum</label>
    <input type="number" name="sum" id="sum" value="{{ sum0 }}" required> <br/>
    <label for="is">Is</label>
    <input type="text" name="is" id="is" value="{{ spending_or_salary }}" required> <br/>

    <button type="reset">Reset</button>
    <button type="submit">Submit</button>
  </form>
</body>
</html>

app/templates/spendings/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Spendings</title>
</head>
<body>
    <h1>Spendings</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Category</th>
                <th>Date</th>
                <th>Sum</th>
                <th>Is</th>
            </tr>
        </thead>
        <tbody>

            {% for spending in spendings%}
             <tr>
                <td>{{ spending.name }}</td>
                <td>{{ spending.category }}</td>
                <td>{{ spending.date }}</td>
                <td>{{ spending.sum0 }}</td>
                <td>{{ spending.is_spending }}</td>
                <td><button><a href="{{ url_for('spendings.edit_spending', spending_id=spending.id) }}">Edit</a></button></td>
                <td><button><a href="{{ url_for('spendings.delete_spending', spending_id=spending.id) }}">Delete</a></button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>